# /server/swagger.yaml
openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: Swagger yaml @ :8080/api-docs v02 25.0202 1111am
servers:
  - url: http://localhost:8080
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    MyModel:
      type: object
      required:
        - field1
        - field2
        - field3
      properties:
        field1:
          type: string
          description: The first field
        field2:
          type: integer
          description: The second field
        field3:
          type: array
          items:
            type: string
          description: The third field
security:
  - BearerAuth: []
paths:
  /api/register:
    post:
      summary: Register a new user
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '500':
          description: Some server error
  /api/login:
    post:
      summary: Login a user
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User logged in successfully
        '400':
          description: Invalid username or password
        '500':
          description: Some server error
  /api/users:
    get:
      summary: Get all users
      tags:
        - User
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    username:
                      type: string
        '500':
          description: Some server error
  /api/create:
    post:
      summary: Create a new document
      tags:
        - MyModel
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MyModel'
      responses:
        '200':
          description: The created document
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyModel'
        '500':
          description: Some server error
  /api/read:
    get:
      summary: Retrieve a list of documents
      tags:
        - MyModel
      security:
        - BearerAuth: []
      responses:
        '200':
          description: A list of documents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MyModel'
        '500':
          description: Some server error